
SELECT * FROM customer_behavior.customer_shopping_behavior;

 -- Q1 what  is the total revenue generated by male vs. female customers? --
 
 Select gender, sum(Purchase_Amount) as total_revenue from customer_shopping_behavior group by Gender;
 
 -- Q2 Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id,
    purchase_amount
FROM 
    customer_shopping_behavior
WHERE 
    discount_applied = 'Yes'
    AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_shopping_behavior);

-- Q3 Which are the top 5 products with the highest average review rating?

Select item_purchased as Products,
	round(avg(review_rating),2) as avg_product_rating from customer_shopping_behavior 
       group by products order by avg_product_rating desc limit 5;

-- Q4 Compare the average purchase amounts between standard and express shipping ?

Select shipping_type, round(avg(purchase_amount),2) as average
 from customer_shopping_behavior
where shipping_type in( 'standard' ,'express') group by shipping_type ;

-- Q5 Do subscribed customers spend more? compare average spend and total revenue between subscribers and non subscribers --

Select subscription_status,
count(customer_id) as total_customers,
avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue
from customer_shopping_behavior
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

Select item_purchased, 
   Round(100 * sum(case when discount_applied = 'Yes' Then 1 Else 0 End)/count(*),2) as discount_rate
 from customer_shopping_behavior group by item_purchased order by discount_rate desc limit 5;
 
 -- Q7 Segment customers into new, returing, and loyal based on their total number of previous purchases, and show the count of each segment?
 
 with customer_types as (
 select customer_id, previous_purchases,
 Case
 When previous_purchases = 1 Then 'New'
 When previous_purchases  Between 2 and 10 Then 'Returning'
 Else 'Loyal'
 End as customer_segment from customer_shopping_behavior
 )
 Select customer_segment, count(customer_id) as 'Numbers of customers'
 from customer_types
 group by customer_segment;
 
 -- Q8 What are the top 3 most purchased products within each category?
 
WITH product_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rn
    FROM 
        customer_shopping_behavior
    GROUP BY 
        category, item_purchased
)
SELECT 
    category,
    item_purchased,
    purchase_count
FROM 
    product_counts
WHERE 
    rn <= 3
ORDER BY 
    category, rn; 
    
    -- Q9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
    
   Select subscription_status, count(customer_id) as repeat_buyers from customer_shopping_behavior
   where previous_purchases > 5 
   group by subscription_status;
 
 -- Q.10 What is the revenue contribution of each age group?
 
Select age_group,
sum(purchase_amount) as total_revenue
from customer_shopping_behavior
group by age_group
order by total_revenue desc;

 